variables: 
- name: NUGET_ARTIFACTS
  value: 'dbpdfium-nuget-artifacts'
- name: PACKAGE_DIR
  value: 'Drawboard.PDFium'
- name: PACKAGE_ID
  value: 'Drawboard.PDFium.UWP'

stages:
- stage: Build
  jobs:
   - job: BuildAndPack
     displayName: 'Build and Pack'
     pool:
      name: 'Default'
      vmImage: 'windows-latest'
     steps:
      - checkout: self
        submodules: 'true'

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '6.x'

      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: '6.x'

      - task: NuGetAuthenticate@1
        displayName: 'Authenticate DevOpsNuget repository'
        # don't need other inputs because the nuget feed is in the Drawboard organization

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            dotnet build src/PDFiumCoreBindingsGenerator/PDFiumCoreBindingsGenerator.csproj -c Release
            dotnet ./src/PDFiumCoreBindingsGenerator/bin/Release/net6.0/PDFiumCoreBindingsGenerator.dll latest true
            dotnet pack ./src/PDFiumCore/PDFiumCore.csproj -c Release --output $(Build.SourcesDirectory)/bin/$(PACKAGE_DIR) -p:PackageID=$(PACKAGE_ID) -p:PackageProjectUrl='https://github.com/DrawboardLtd/PDFiumCore' -p:RepositoryUrl='https://github.com/DrawboardLtd/PDFiumCore'
            # dotnet test ./src/PDFiumCore.Tests/PDFiumCore.Tests.csproj

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifacts'
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/bin/$(PACKAGE_DIR)'
          ArtifactName: $(NUGET_ARTIFACTS)

- stage: PublishNugetOnAzureDevops 
  # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  dependsOn: Build
  jobs:  
  - job: PublishNugetJob
    pool:
      name: 'Default'
      vmImage: 'windows-latest'
    steps:
    - checkout: none
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: current
        artifactName: $(NUGET_ARTIFACTS)
        downloadPath: '$(System.ArtifactsDirectory)'

    - script: |
        dir $(System.ArtifactsDirectory)\$(NUGET_ARTIFACTS)
      displayName: List downloaded nuget artifacts

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '6.x'

    - task: NuGetAuthenticate@1
      displayName: 'Authenticate DevOpsNuget repository'
      # don't need other inputs because the nuget feed is in the Drawboard organization

    - task: NuGetCommand@2
      displayName: 'NuGet publish'
      inputs:
        command: push
        nuGetFeedType: internal
        feedPublish: Drawboard.PDFium.UWP
        packagesToPush: '$(System.ArtifactsDirectory)\$(NUGET_ARTIFACTS)\*.nupkg'
        allowPackageConflicts: true
